version: '2'

services:
  postgres:
    image: 'postgres:13'
    env_file: 
      - '.env'
    volumes: 
      - 'postgres:/var/lib/postgresql/data'
    ports: 
      - '5432:5432'
    # needed because the postgres container does not provide a healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_api"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "hotel_api.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/hotel_api'
    ports:
      - '8000:8000'
volumes:
  postgres: