name: integration-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
            envkey_COMPOSE_PROJECT_NAME: hotel_api
            envkey_PROD: false
            envkey_PORT: 8000
            file_name: .env
      - name: Build app
        run: docker-compose up -d
      - name: Create and seed db
        run: docker-compose exec -T api hotel_api db reset --with-testdb --dev
      - name: Run tests
        run: docker-compose exec -T api py.test hotel_api/tests